### ISSUE TITLE
有没有Android Studio可运行的项目， 需要系统权限吗， 这个只能在源码中一起编译吗

### ISSUE THREAD

**Issue by MarkTsy** [without1022/BT_sink#1]

**Comment by without1022** [comment]
这个是源码级别的项目，打电话以及音乐播放控制都是使用的安卓源码，代码成熟，懒得改，因为安卓默认是source配置的，所以得修改源码配置变成sink配置才能支持这两个功能。
短信获取或者通信录获取，这里重新封装了一遍，不修改源码也可以支持，源码都在拷到as里就能编译，由于我不怎么用as，所以没有单独提供as项目

**Comment by MarkTsy** [comment]
感谢答复， 我是面向应用层开发的 不太了解源码的编译 ， 不知道你有没有相关的博客 可供学习观摩

**Comment by without1022** [comment]
https://blog.csdn.net/lishengo0/article/details/80680856

**Comment by without1022** [comment]
https://blog.csdn.net/lishengo0/article/details/80680856；https://www.cnblogs.com/fuyaozhishang/p/7639675.html；https://github.com/louisjang/A2dpSinkTest/blob/master/java/com/windriver/a2dpsinktest/A2dpSinkRoutingService.java；https://blog.csdn.net/bingsiju123123/article/details/53065108；https://blog.csdn.net/kafka_88/article/details/50670406#comments；https://blog.csdn.net/u012439416/article/details/54349812；https://blog.csdn.net/u010347226/article/details/77688822；

**Comment by without1022** [comment]
这是我当时开发时参考的博客，希望对你有用

**Comment by without1022** [comment]
提醒一句，不修改源码的话，蓝牙连接上会优先走一边原生安卓apk；没关掉相关配置，使用这些功能会和安卓原生蓝牙应用产生冲突，只尝试过修改源码规避掉，未尝试其他方法规避

**Comment by MarkTsy** [comment]
thks so much
