### ISSUE TITLE
可以说一下怎么编译的吗？

### ISSUE THREAD

**Issue by JosephTF** [without1022/BT_sink#2]
另外packages.diff 中的Config.java没在源码中找到。

**Comment by JosephTF** [comment]
> 另外packages.diff 中的Config.java没在源码中找到。

准确的说是Config修改的那两行代码没找到，包括addAudioProfiles方法也没找到。

**Comment by without1022** [comment]
可以放到安卓源码里使用` mmma code_path` 编译(android.mk文件已提供)，也可以将代码导入androidstudio编译（暂时得自己导入，后续我会更新下提供出as工程），我去官网看了谷歌代码，addAudioProfiles确实没找到，可能是我们的代码被高通改过，本来这个函数里的两句导致了a2dp_sink和hfp_client无法连接，没有的话更好，省的麻烦，你打开a2dp_sink和hfp的配置能连上就不用去管那两句代码了

**Comment by without1022** [comment]
我是基于高通平台开发的，源码可能跟谷歌的稍有不同，搞清楚那处代码修改的原由适当调整即可，这边 修改源码配置主要是放开a2dp_sink,hfp_client,和avrcp_controller的连接
